[tool.poetry]
name = "museum-ai"
version = "0.1.0"
description = ""
authors = ["Twsoen <Twsoen@qq.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
chromadb = "^1.1.1"
loguru = "^0.7.2"
beautifulsoup4 = "^4.14.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
